### ISSUE TITLE
Bracket highlighting uses unpleasant color

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/victis-syntax#3]
![screen shot 2018-02-19 at 4 46 20 pm](https://user-images.githubusercontent.com/5923662/36437659-992796b4-1635-11e8-93a1-4e2f79d38d62.png)

I don't like that green color.

**Comment by ianzullo** [comment]
honestly im fine with using blue here. we've used blue for bumpers and it kinda blends in as red
thoughts?
![screen shot 2018-02-20 at 8 13 53 pm](https://user-images.githubusercontent.com/15891996/36457995-cb91d908-167a-11e8-906f-ee63e690b4f4.png)
![screen shot 2018-02-20 at 8 14 02 pm](https://user-images.githubusercontent.com/15891996/36457996-cb9b0dca-167a-11e8-816b-92e875d6bb88.png)

**Comment by ErikBoesen** [comment]
Hm... I'd prefer keeping it red... blue is okay though.
