### ISSUE TITLE
Find/Replace selected search results have ugly border

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/victis-syntax#4]
![](https://user-images.githubusercontent.com/5923662/36437700-b8e6af08-1635-11e8-8f03-7c7f5ea36b90.png)

They should just have the lighter gray background; we don't need the black border.

**Comment by ianzullo** [comment]
this is different for me. 
![image](https://user-images.githubusercontent.com/15891996/36452742-a2d7bd8c-1663-11e8-8245-0f0f3225c5db.png)

**Comment by ianzullo** [comment]
selected:
![screen shot 2018-02-20 at 5 44 32 pm](https://user-images.githubusercontent.com/15891996/36453345-c31c98ea-1665-11e8-974c-0a48bd2f1758.png)

**Comment by ErikBoesen** [comment]
Huh... UI theme issue then?

**Comment by ianzullo** [comment]
It shouldn't be, it's right there in the code that my second screenshot has.

**Comment by ianzullo** [comment]
what do you think about this? 
![screen shot 2018-02-20 at 6 41 32 pm](https://user-images.githubusercontent.com/15891996/36455368-c024aca6-166d-11e8-83f2-ff0764951fc2.png)

**Comment by ErikBoesen** [comment]
I like that. Square corners are fine.
